In [21]:
import pandas as pd

df=pd.read_csv("Data.csv")
df.head(10)

,Student_ID,Name,Class,Math,Science,English,Computer,Social,Average,Grade,Result
0,ST0001,Sneha Sharma,IT-B,95,51,55,23,73,59.4,D,Fail
1,ST0002,Meera Iyer,ECE-A,87,30,64,26,94,60.2,C,Fail
2,ST0003,Aishwarya Singh,IT-A,24,29,92,80,35,52.0,D,Fail
3,ST0004,Sneha Jain,ECE-A,56,92,72,73,37,66.0,C,Pass
4,ST0005,Divya Bose,ECE-A,91,97,49,87,78,80.4,A,Pass
5,ST0006,Vivek Kumar,CSE-B,50,96,79,98,35,71.6,B,Pass
6,ST0007,Priya Reddy,IT-A,28,76,51,20,25,40.0,F,Fail
7,ST0008,Nisha Iyer,IT-A,70,44,86,74,76,70.0,B,Pass
8,ST0009,Sanjay Chopra,IT-A,48,21,86,22,66,48.6,F,Fail
9,ST0010,Priya Jain,ECE-A,97,83,47,97,67,78.2,B,Pass

In [22]:
df.tail()

,Student_ID,Name,Class,Math,Science,English,Computer,Social,Average,Grade,Result
995,ST0996,Kavya Nair,CSE-B,67,57,41,83,32,56.0,D,Fail
996,ST0997,Naveen Chopra,CSE-A,56,47,30,83,75,58.2,D,Fail
997,ST0998,Rahul Bose,CSE-A,34,40,77,21,37,41.8,F,Fail
998,ST0999,Ananya Sharma,IT-B,54,73,76,95,73,74.2,B,Pass
999,ST1000,Divya Kumar,IT-A,90,37,96,61,96,76.0,B,Pass

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  1000 non-null   object
 1   Name        1000 non-null   object
 2   Class       1000 non-null   object
 3   Math        1000 non-null   int64
 4   Science     1000 non-null   int64
 5   English     1000 non-null   int64
 6   Computer    1000 non-null   int64
 7   Social      1000 non-null   int64
 8   Average     1000 non-null   float64
 9   Grade       1000 non-null   object
 10  Result      1000 non-null   object
dtypes: float64(1), int64(5), object(5)
memory usage: 86.1+ KB

In [24]:
df.columns

Index(['Student_ID', 'Name', 'Class', 'Math', 'Science', 'English', 'Computer',
       'Social', 'Average', 'Grade', 'Result'],
      dtype='object')

In [25]:
df.describe()

,Math,Science,English,Computer,Social,Average
count,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,59.48800,57.971000,60.427000,60.906000,59.957000,59.749800
std,23.15634,23.028645,22.726178,23.503352,23.210038,10.265789
min,20.00000,20.000000,20.000000,20.000000,20.000000,26.800000
25%,39.00000,38.000000,41.000000,40.000000,40.000000,52.750000
50%,59.00000,57.000000,61.000000,61.500000,60.500000,60.000000
75%,79.00000,78.000000,79.000000,81.000000,79.000000,66.800000
max,100.00000,100.000000,100.000000,100.000000,100.000000,91.800000

In [26]:
df.isnull().sum()

Student_ID    0
Name          0
Class         0
Math          0
Science       0
English       0
Computer      0
Social        0
Average       0
Grade         0
Result        0
dtype: int64

Calculate Total marks

In [27]:
subjects = ['Math','Science','English','Computer']
df['Total'] = df[subjects].sum(axis=1)

df[['Name','Total']].head()

              Name  Total
0     Sneha Sharma    224
1       Meera Iyer    207
2  Aishwarya Singh    225
3       Sneha Jain    293
4       Divya Bose    324

Calculate Average Marks

In [28]:
df['Average']=df[subjects].mean(axis=1)
df[['Name','Average']].head(7)

              Name  Average
0     Sneha Sharma    56.00
1       Meera Iyer    51.75
2  Aishwarya Singh    56.25
3       Sneha Jain    73.25
4       Divya Bose    81.00
5      Vivek Kumar    80.75
6      Priya Reddy    43.75

Assigning Grades

In [29]:
def grade(avg):
  if avg >=90:
    return 'A+'
  elif avg >=80:
    return 'A'
  elif avg >=70:
    return 'B'
  elif avg >=60:
    return 'C'
  elif avg >=50:
    return 'D'
  else:
    return 'F'
df['Grade'] = df['Average'].apply(grade)
df[['Name','Average','Grade']].head(7)

              Name  Average Grade
0     Sneha Sharma    56.00     D
1       Meera Iyer    51.75     D
2  Aishwarya Singh    56.25     D
3       Sneha Jain    73.25     B
4       Divya Bose    81.00     A
5      Vivek Kumar    80.75     A
6      Priya Reddy    43.75     F

Subject-Wise Average mark

In [30]:
df[subjects].mean()

Math        59.488
Science     57.971
English     60.427
Computer    60.906
dtype: float64

Highest Mark in Each subject

In [31]:
df[subjects].max()

Math        100
Science     100
English     100
Computer    100
dtype: int64

Lower Mark in Each Subject

In [32]:
df[subjects].min()

Math        20
Science     20
English     20
Computer    20
dtype: int64

Student scoring above 90 in maths

In [33]:
df[df['Math']>90]

,Student_ID,Name,Class,Math,Science,English,Computer,Social,Average,Grade,Result,Total
0,ST0001,Sneha Sharma,IT-B,95,51,55,23,73,56.00,D,Fail,224
4,ST0005,Divya Bose,ECE-A,91,97,49,87,78,81.00,A,Pass,324
9,ST0010,Priya Jain,ECE-A,97,83,47,97,67,81.00,A,Pass,324
28,ST0029,Ananya Iyer,IT-B,92,22,56,75,36,61.25,C,Fail,245
31,ST0032,Karthik Verma,IT-B,93,89,84,40,55,76.50,B,Pass,306
...,...,...,...,...,...,...,...,...,...,...,...,...
970,ST0971,Divya Reddy,IT-B,91,92,93,37,83,78.25,B,Pass,313
972,ST0973,Rohit Agarwal,ECE-A,99,47,27,42,53,53.75,D,Fail,215
982,ST0983,Ananya Patel,IT-B,93,100,28,97,46,79.50,B,Fail,318
986,ST0987,Aishwarya Yadav,ECE-A,93,84,80,97,52,88.50,A,Pass,354
993,ST0994,Sanjay Nair,CSE-B,100,42,37,26,53,51.25,D,Fail,205